# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-13 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='message',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wall.Messages'),
            preserve_default=False,
        ),
    ]
